export const routePaths = {
  home: "/",
  pricing: "/pricing",
  growth: "/growth",
  about: "/about",
  terms: "/terms",
  privacy: "/privacy",
  managedIt: "/managed-it",
  familyProtection: "/family-protection",
  fractionalLeadership: "/fractional-leadership",
  nonProfits: "/non-profits",
  contact: "/contact",
  industries: "/industries",
  services: "/services",
  talkToSales: "/talk-to-sales",
  personal: "/personal",
  seniorCare: "/senior-care",
  crisisManagement: "/crisis-management",
  colophon: "/colophon",
  ethics: "/ethics",
  resources: "/resources",
  status: "/status",
  support: "/support",
  clientCare: "/client-care",
} as const;

export type RoutePath = (typeof routePaths)[keyof typeof routePaths];
